mqtt:
  host: '{{ mqtt_host }}'
  port: {{ mqtt_port }}
  user: '{{ mqtt_user }}'
  password: '{{ mqtt_password }}'
  client_id: '{{ ansible_host }}-akdfjwqq'
  topic_prefix: '{{ ansible_host }}'
  tls:
    enabled: true
  ha_discovery:
    enabled: yes
  status_payload_running: available
  status_payload_stopped: unavailable
  status_payload_dead: unavailable

gpio_modules:
  # Use the Raspberry Pi built-in GPIO
  - name: rpi
    module: raspberrypi

digital_inputs:
  - name: motion_sensor
    module: rpi
    pin: 27

digital_outputs:
  - name: living_lamp
    module: rpi
    pin: 17
    inverted: true
