mqtt:
  host: '{{ mqtt_host }}'
  port: {{ mqtt_port }}
  user: '{{ mqtt_user }}'
  password: '{{ mqtt_password }}'
  client_id: '{{ mqtt_client_id }}'
  topic_prefix: '{{ ansible_host }}'
  tls:
    enabled: {{ mqtt_tls_enabled }}
  ha_discovery:
    enabled: yes
  status_payload_running: available
  status_payload_stopped: unavailable
  status_payload_dead: unavailable

gpio_modules:
  # Use the Raspberry Pi built-in GPIO
  - name: rpi
    module: raspberrypi

digital_inputs:
  - name: top_button
    module: rpi
    pin: 17
    bouncetime: 30
    ha_discovery:
      name: "Top button"
  - name: bottom_button
    module: rpi
    pin: 27
    bouncetime: 30
    ha_discovery:
      name: "Bottom button"

digital_outputs:
  - name: red_led
    module: rpi
    pin: 10
    retain: true
    ha_discovery:
      name: "RED"
  - name: green_led
    module: rpi
    pin: 9
    retain: true
    ha_discovery:
      name: "GREEN"
  - name: kitchen_lamp
    module: rpi
    pin: 18
    inverted: true
    retain: true
    ha_discovery:
      name: "Kitchen light"

sensor_modules:
  - name: dht_sensor
    module: dht22
    type: dht11
    pin: 22

sensor_inputs:
  - name: dht_humidity
    module: dht_sensor
    type: humidity
    interval: 4
    ha_discovery:
      name: "Humidity"
  - name: dht_temperature
    module: dht_sensor
    type: temperature
    interval: 6
    ha_discovery:
      name: "Temperature"
