#!/bin/ansible-playbook

- hosts:
    - raspi-1
    - raspi-3
  vars:
    mqtt_host: burelli.xyz
    mqtt_port: 8883
  become: yes
  tasks:
    - name: ReStart mqtt-camera service
      ansible.builtin.systemd:
        state: restarted
        name: mqtt-camera
        daemon_reload: true
        enabled: true
