#!/bin/ansible-playbook

- hosts:
    - raspi-1
    - raspi-2
  vars:
    mqtt_host: burelli.xyz
    mqtt_port: 8883
  become: yes
  tasks:
    - name: ReStart mqtt-io service
      systemd: enabled=yes state=restarted name=mqtt-io daemon_reload=yes
