#!/bin/ansible-playbook

- hosts: raspi-1
  become: yes
  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        autoremove: yes
        state: present
        pkg:
          - dnsutils
          - vim
          - git
          - pigpio
          - pigpiod
          - mosquitto-clients
