#!/bin/ansible-playbook

- hosts:
    - raspi_camera
  become: yes
  tasks:
    - name: ReStart mqtt-camera service
      ansible.builtin.systemd:
        state: restarted
        name: mqtt-camera
        daemon_reload: true
        enabled: true
